### ISSUE TITLE
2 heavenly upgrade missing

### ISSUE THREAD

**Issue by Catwhynot-Dev** [mrbuilder1961/mrbuilder1961.github.io#2]
the heavenly upgrade lucky payout and lucky number are missing, but it shows in the upgrade calculator

**Comment by mrbuilder1961** [comment]
Please elaborate or attach a screenshot, do you mean they don't show up as purchased but they do in the calculator?

**Comment by Catwhynot-Dev** [comment]
her
![Screenshot 2021-12-01 8 39 30 PM](https://user-images.githubusercontent.com/94798292/144341896-5553d973-bcab-4948-abec-7a533cabe068.png)
![Screenshot 2021-12-01 8 39 02 PM](https://user-images.githubusercontent.com/94798292/144341897-acde9536-7fa3-4a3d-92ae-9d98c4bcb214.png)
e

**Comment by mrbuilder1961** [comment]
Oh, that's how the game works. To buy lucky digit, number, and payout, you have to have your amount of new heavenly chips (how many you gain when you ascend) end in 7, 777, and 777777 respectively.

**Comment by Catwhynot-Dev** [comment]
oh thanks
